[package]
name = "wizard"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies.amethyst]
git = "https://github.com/amethyst/amethyst.git"
branch = "master"

[features]
default = ["metal"]
empty = ["amethyst/empty"]
metal = ["amethyst/metal"]
vulkan = ["amethyst/vulkan"]
